### PR TITLE
Semester and Semester byproducts

### PR DESCRIPTION
**Pull request by toasterbrain**
Okay, this is a little buggy and a lot late but I suppose it's time to pass the torch.
I believe the plan was for us to get this merged even though it only kinda works such that chris and I can debug it this sprint.

### CODE REVIEW

**Comment by toasterbrain** [comment]
can anyone tell by the commit history that I was fighting with git?

**Comment by Brodski** [comment]
I think this pull request might be a bit outdated, it seems like it wants to delete some of our newer code, like in courseControler and in index, for example

But anyways, I already have been working with your code, so maybe instead I could just do a pull request with my code (which is using your code already)

**Comment by toasterbrain** [comment]
i would like to get at least one moderately sized PR merged at some point. this seems like the best time to do it. I will fix the issue with courseController and index and update this.

**Comment by Brodski** [comment]
you should update your repository with our master & dev branch. Just google "sync a repo with master" and the first result by git should do it

**Comment by Brodski** [comment]
i think that would be easiest for you

**Comment by Brodski** [comment]
https://help.github.com/articles/syncing-a-fork/

but instead of using "master you use "development" . ie:

git fetch upstream
git checkout development
git merge upstream/development

**Comment by toasterbrain** [comment]
okay it should be fixed.

**Pull request merged**
