### PR TITLE
initial scaffolding for MVC

### PR DESCRIPTION
**Pull request by cblanto7**
This is a barebones Web-App that serves up an index.html and is built using Gradle.

See the readme for info on how to launch the app

### CODE REVIEW

**Comment by cblanto7** [comment]
Probably should be on the development branch but I wanted to get a starting point up for the group to work on and build from

**Comment by Brodski** [comment]
It works for me. BUT, I kinda read and attempted the article that was linked in the readme, though I dont really understand it :|

**Comment by toasterbrain** [comment]
It's a good thing that all checks have failed right?
It feels suspiciously easy that this is all I have to do to review stuff.

**Comment by cblanto7** [comment]
ok cool I will add those to .gitignore

**Pull request closed without merging**
